In [5]:
import numpy as np


In [11]:
mydizi=np.arange(0,10)

In [12]:
mydizi

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
mydizi[1:3]

array([1, 2])

In [14]:
mydizi[1:3]=65

In [15]:
mydizi

array([ 0, 65, 65,  3,  4,  5,  6,  7,  8,  9])